apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-storage-operators
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-storage-controllers
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
