kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-snapshot-controller-operator-role
  namespace: openshift-cluster-storage-operators
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: csi-snapshot-controller-operator
    namespace: openshift-cluster-storage-operators
roleRef:
  kind: ClusterRole
  name: cluster-admin
